from litemapy import Region


def export_region(region: Region, filename: str, name: str = "Atlas Export"):
    schematic = region.as_schematic(
        name=name,
        author="Atlas",
        description="Generated by Atlas"
    )

    print("Blocks in region:", region.count_blocks())

    schematic.save(filename)

    print(f"Saved {filename}")